spring.datasource.url=jdbc:mysql://localhost:3306/rentals_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Manaseh@123

spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=run

spring.jpa.show-sql=true
server.port=8080
server.address=127.0.0.1
java.awt.headless=false
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**